name: Build and Push Redshift Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - p

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - p

env:
  DOTNET_VERSION: "8.0.100"
  IMAGE_NAME: redshift

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push
