name: Build and Push to Production

on:
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

env:
  REGION: ""
  CLUSTER: ""
  NAMESPACE: ""
  TAG: "prod"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker-compose build --no-cache --force-rm

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push scooters_db image
        uses: docker/build-push-action@v5
        with:
          context: ./scooters_db
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scooters_server:${{ env.TAG }}

      - name: Build and push scooters_server image
        uses: docker/build-push-action@v5
        with:
          context: ./scooters_server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scooters_server:${{ env.TAG }}

      - name: Build and push scooters_web image
        uses: docker/build-push-action@v5
        with:
          context: ./scooters_web
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scooters_web:${{ env.TAG }}
